create table public.pending_user (
  pending_user_id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  role_id uuid not null,
  first_name text not null,
  middle_name text null,
  last_name text not null,
  profile_picture text null,
  created_at timestamp with time zone not null default now(),
  constraint pending_user_pkey primary key (pending_user_id),
  constraint pending_user_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table auth.users (
  id uuid not null,
  aud character varying(255) null,
  role character varying(255) null,
  email character varying(255) null,
  phone text null default null::character varying,
) TABLESPACE pg_default;




create table public.user_roles (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  role_id bigint not null,
  constraint user_roles_pkey primary key (id),
  constraint unique_user_role unique (user_id, role_id),
  constraint user_roles_id_key unique (id),
  constraint user_roles_role_id_fkey foreign KEY (role_id) references roles (id),
  constraint user_roles_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create index IF not exists idx_user_id on public.user_roles using btree (user_id) TABLESPACE pg_default;
create index IF not exists idx_role_id on public.user_roles using btree (role_id) TABLESPACE pg_default;


create table public.account_status (
  account_status_id uuid not null default gen_random_uuid (),
  status public.accountStatus not null default 'PENDING'::"accountStatus",
  constraint Account Status_pkey primary key (account_status_id)
) TABLESPACE pg_default;


create table public.account (
  account_id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  first_name text not null default ''::text,
  middle_name text null default ''::text,
  last_name text not null default ''::text,
  profile_picture text null default ''::text,
  account_status public.accountStatus null default 'PENDING'::"accountStatus",
  constraint account_pkey primary key (account_id),
  constraint account_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;